---
# vars file for awx
awx_package_dependencies:
  - git 
  - gcc
  - gcc-c++
  - nodejs
  - device-mapper-persistent-data
  - gettext
  - lvm2
  - bzip2
  - python3-pip
  
awx_repo: https://github.com/ansible/awx.git
awx_repo_dir: "~/awx"
awx_version: devel
awx_keep_updated: true
awx_run_install_playbook: true
postgres_data_dir: /var/lib/pgdocker
